# Generated by Django 4.2.30 on 2026-06-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="content",
        ),
        migrations.AddField(
            model_name="resume",
            name="is_ai_enhanced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="template",
            field=models.CharField(
                choices=[
                    ("modern", "Modern"),
                    ("classic", "Classic"),
                    ("minimal", "Minimal"),
                ],
                default="modern",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(default="Untitled Resume", max_length=100),
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField()),
                ("ai_enhanced_text", models.TextField(blank=True)),
                ("use_ai_version", models.BooleanField(default=True)),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("soft", "Soft"),
                            ("language", "Language"),
                            ("tool", "Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("proficiency", models.PositiveIntegerField(default=3)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ("-proficiency",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ai_enhanced_description", models.TextField(blank=True)),
                ("tech_stack", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("raw_description", models.TextField()),
                ("ai_enhanced_description", models.TextField(blank=True)),
                ("use_ai_version", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-start_date"),
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("start_year", models.PositiveIntegerField()),
                ("end_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("honors", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-start_year"),
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("issuer", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_url", models.URLField(blank=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ("-issue_date",),
            },
        ),
    ]
