# Generated by Django 5.2.15 on 2026-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_remove_resume_content_resume_is_ai_enhanced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="public_slug",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
