# Generated by Django 4.2.30 on 2026-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_is_public_resume_public_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="github",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="linkedin",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="portfolio",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
