# Generated by Django 4.2.30 on 2026-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_alter_personalinfo_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
