# Generated by Django 4.2.30 on 2026-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_alter_personalinfo_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="target_job_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
