# Generated by Django 4.2.30 on 2026-06-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0006_summary_target_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="raw_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
